include .env


MIGRATE=migrate -path=migration -database "postgresql://$(DB_USER):$(DB_PASS)@($(DB_HOST):$(DB_PORT))/$(DB_NAME)" -verbose

migrate-up:
		$(MIGRATE) up
migrate-down:
		$(MIGRATE) down 
force:
		@read -p  "Which version do you want to force?" VERSION; \
		$(MIGRATE) force $$VERSION

goto:
		@read -p  "Which version do you want to migrate?" VERSION; \
		$(MIGRATE) goto $$VERSION

drop:
		$(MIGRATE) drop

create:
		@read -p  "What is the name of migration?" NAME; \
		$(MIGRATE) create -ext sql -seq -dir migration  $$NAME

.PHONY: migrate-up migrate-down force goto drop create